name: ontdekkendleren
favicon: null
layout_spectrum: 0.43681226088665426
typography_spectrum: 0.4899250837042928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.268515833420679
  lightness: 0.350459803128615
  saturation: 0.6622902294620872
  rhythmicContrast: 0.9547221991233528
purpose: []
