name: ontdekkend leren
favicon: null
layout_spectrum: 0.43681226088665426
typography_spectrum: 0.4899250837042928
title: 'Spelen, ontdekken, leren'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6fb63a'
    - '#924a97'
    - '#00a8e5'
    - '#fab423'
    - '#ffffff'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
