name: ontdekkend leren
favicon: null
layout_spectrum: 0.74513
typography_spectrum: 0.65235
title: 'Spelen, ontdekken, leren'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#94c120'
    - '#f07d00'
    - '#662583'
    - '#f6a9d4'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
